services:
  n8-wa1-ubi8:
    image: localhost/n8-wa1-ubi8:0.0.1
    ports:
      - 8081:8080
    volumes:
      - ./certs:/etc/certs:Z
    environment:
      ASPNETCORE_URLS: "https://+:8080"
      ASPNETCORE_ENVIRONMENT: "Container"
  n8-wa1-ubi8-fips:
    image: localhost/n8-wa1-ubi8:0.0.1
    ports:
      - 8082:8080
    volumes:
      - ./certs:/etc/certs:Z
    environment:
      ASPNETCORE_URLS: "https://+:8080"
      ASPNETCORE_ENVIRONMENT: "Container"
      OPENSSL_FORCE_FIPS_MODE: 1
  n6-wa1-ubi8-fips:
    image: localhost/n6-wa1-ubi8:0.0.1
    ports:
      - 8083:8080
    volumes:
      - ./certs:/etc/certs:Z
    environment:
      ASPNETCORE_URLS: "https://+:8080"
      ASPNETCORE_ENVIRONMENT: "Container"
      OPENSSL_FORCE_FIPS_MODE: 1
  n8-wa1-fedora-fips:
    image: localhost/n8-wa1-fedora:0.0.1
    ports:
      - 8084:8080
    volumes:
      - ./certs:/etc/certs:Z
    environment:
      ASPNETCORE_URLS: "https://+:8080"
      ASPNETCORE_ENVIRONMENT: "Container"
      OPENSSL_FORCE_FIPS_MODE: 1
  n6-wa1-fedora-fips:
    image: localhost/n6-wa1-fedora:0.0.1
    ports:
      - 8085:8080
    volumes:
      - ./certs:/etc/certs:Z
    environment:
      ASPNETCORE_URLS: "https://+:8080"
      ASPNETCORE_ENVIRONMENT: "Container"
      OPENSSL_FORCE_FIPS_MODE: 1
